### ISSUE TITLE
Question: lancache-rpi vs Lancache.NET

### ISSUE THREAD

**Issue by ghost** [jrcichra/lancache-rpi#9]
I already have a cache directory for Lancache.NET. Can I use lancache-rpi to write to the same cache directory or it is better to write to a different cache directory? Also, if I keep separate cache directories can I merge them together later?

**Comment by ghost** [comment]
Maybe the title of this "issue" (more like question) needs to be changed.

**Comment by CyberoniOntoni** [comment]
It really depends. If chunk size specified in both instances is the same, then the odds are - it will work. If chunk sizes are different, then it either might not read your cache, or might read some of it.

**Comment by jrcichra** [comment]
It should work on the same cache - the only difference here is I compile their containers for arm instead of x86. In theory, the data output to disk should be the same (assuming like @CyberoniOntoni said, you're using the same chunk size)

I can't speak to merging cache's together. I'm unfamiliar with nginx's caching technique. That may be a question for the official lancache.net maintainers. Can't hurt to try with some fresh data (or clones of your existing data if you have zfs or btrfs [ or straight cps]).
